config/routes.rb
Mafia::Application.routes.draw do

  devise_for :users, :path_prefix => 'my'
  resources :users do
    resources :player_roles
  end

  resources :games do
    get :best_player
    resources :rounds
    resources :players do
      collection do
        post :create_bunch
        put :put_roles
        put :put_remarks
      end

      member do
        #get :score
        get :set_role
        delete :destroy_all
        get :get_remarks
      end
    end
  end

  resources :scores
  root :to => 'games#index'
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name, :alias, :role_ids
  # attr_accessible :title, :body

  has_many :players
  has_many :games, :through => :players
  has_many :managers

  validates :name, exclusion: {in: %w(admin superuser moderator),
                              message: "%{value} is reserved.'"}

  after_create :set_permission!

  def self.search(search)
    if search
      where('alias LIKE ? OR name LIKE ?',"%#{search}%", "%#{search}%")
    else
      scoped
    end
  end

  def set_permission!
    add_role 'player'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource
  helper_method :sort_column, :sort_direction
  before_filter :user_scoped
  respond_to :html


  def index
    @users = User.order(sort_column + ' ' + sort_direction).paginate(page: params[:page], per_page: 10).search(params[:search])
    respond_with do |format|
      format.html {
        render :partial => 'users/table' if request.xhr?
      }
    end
  end

  def show

  end

  def edit

  end

  def update
    @user.update_attributes(params[:user])
    redirect_to users_path
  end

  def new

  end

  def create
    @user = User.create(params[:user])
    binding.pry
    redirect_to users_path
  end

  def destroy
    @user.destroy
    redirect_to users_path
  end


  private


  def user_scoped
    @users = User.scoped
  end

  def sort_column
    User.column_names.include?(params[:sort_column]) ? params[:sort_column] : 'created_at'
  end

  def sort_direction

    %w[asc desc].include?(params[:sort_direction]) ? params[:sort_direction] : 'asc'
  end
end

app/views/users/_table.html.haml
%table.table.table-striped.table-bordered.bordered.zebra

  %thead
    %tr
      %th{:style => 'width: 10%'} User ID
      %th{:style => 'width: 10%'}=sortable 'name','name'
      %th{:style => 'width: 10%'} E-mail
      %th{:style => 'width: 10%'}

    - @users.each do |user|
      %tr
        %td= user.id
        %td= user.name
        %td= user.email
        %td
          .btn-group
            =link_to 'Actions', '', class: 'btn btn-primary dropdown-toggle'
            =link_to '', class: 'btn btn-primary dropdown-toggle' do
              %span.caret
            %ul.dropdown-menu
              %li
                = link_to user_path(user) do
                  %i.icon-th
                  Show
              %li
                = link_to edit_user_path(user) do
                  %i.icon-pencil
                  Edit
              %li
                = link_to user_path(user), method: :delete do
                  %i.icon-trash
                  Destroy
.new
  =link_to "New", new_user_path, class: 'btn btn-primary'
#pagination= will_paginate @users

app/views/users/edit.html.haml
%h2
= simple_form_for(@user, :url => user_path(@user), :html => { :method => :put, :class => 'form-vertical' }) do |f|
  = f.input :name, :autofocus => true
  = f.input :alias
  = f.input :email, :required => true
  = f.input :password, :autocomplete => "off", :required => true
  = f.input :password_confirmation, :required => true
  -#= f.input :current_password, :hint => "we need your current password to confirm your changes", :required => true
  = f.association :roles, as: :radio_buttons if can? :manage_roles, @user
  %br/
  = f.button :submit, 'Update', :class => 'btn-primary'

app/views/users/index.html.haml
%ul.nav.nav-tabs
  %li
    = link_to 'Games', games_path
  %li
    = link_to 'Scores', scores_path
  - if can? :manage_roles, @user
    %li.active
      = link_to 'Users', users_path
= form_tag @user, method: :get, class: 'form-search', id: 'search' do
  .input-append
    = text_field_tag :search, params[:search], class: 'span2 search-query'
    = submit_tag 'Search', class: 'btn'
#sortable_table= render 'users/table'

app/views/users/new.html.haml
= simple_form_for(@user, :rul => new_user_path, html: {method: :post, class: 'form-vertical'}) do |f|
  = f.input :name, :autofocus => true
  = f.input :alias
  = f.input :email, :required => true
  = f.input :password
  = f.input :password_confirmation, :required => false
  = f.association :roles, as: :radio_buttons
  = f.submit
-#
-#%h2 Sign up
-#= form_for(resource, :as => resource_name, :url => registration_path(resource_name)) do |f|
-#  = devise_error_messages!
-#  %div
-#    = f.label :name
-#    %br/
-#    = f.text_field :name
-#  %div
-#    = f.label :nick_name
-#    %br/
-#    = f.text_field :alias
-#  %div
-#    = f.label :email
-#    %br/
-#    = f.email_field :email, :autofocus => true
-#  %div
-#    = f.label :password
-#    %br/
-#    = f.password_field :password
-#  %div
-#    = f.label :password_confirmation
-#    %br/
-#    = f.password_field :password_confirmation
-#  -#%div
-#  -#  %br/
-#  -#  = f.association :roles, as: :select
-#  %div= f.submit "Sign up"
-#= render "devise/shared/links"