config/routes.rb
Mafia::Application.routes.draw do

  devise_for :users, :path_prefix => 'my'
  resources :users do
    resources :player_roles
  end

  resources :games do
    get :best_player
    resources :rounds
    resources :players do
      collection do
        post :create_bunch
        put :put_roles
        put :put_remarks
      end

      member do
        #get :score
        get :set_role
        delete :destroy_all
        get :get_remarks
      end
    end
  end

  resources :scores
  root :to => 'games#index'
end

app/models/game.rb
#require 'services/reference'
class Game < ActiveRecord::Base
  resourcify

  extend FriendlyId
  friendly_id :game_ref

  attr_accessible :game_status, :result, :description, :game_manager, :players_attributes, :best_player, :game_ref, :first_killed_sheriff

  attr_accessor :game_manager

  has_many :players, dependent: :destroy
  has_many :users, :through => :players
  has_one :manager, dependent: :destroy

  accepts_nested_attributes_for :players

  before_create :generate_game_ref
  after_create :create_manager

  validates :description, presence: true

  GAME_RESULT = ['red', 'black'].freeze
  #def methods result_black? result_red?
  GAME_RESULT.each do |type|
    define_method("result_#{type}?") {result.to_s == type}
  end

  def create_manager
    if game_manager
      Manager.create(user_id: self.game_manager, game_id: self.id)
    end
  end

  def status_open?
     game_status == 'open'
  end

  def game_result
    result
  end

  def generate_game_ref
    ::ReferenceService.new(self).create_reference!
  end

  class << self
    def search(search)
      if search
        where('result LIKE ? OR best_player LIKE ? ', "%#{search}%", "%#{search}%")
      else
        scoped
      end
    end
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  load_and_authorize_resource

  helper_method :sort_column, :sort_direction

  before_filter :game_find, except: [:create, :new, :index, :best_player]
  before_filter :user_scoped, except: [:index]
  before_filter :appointment_scoped, only: [:best_player, :show]

  respond_to :html

  def index
    @games = Game.order(sort_column + ' ' + sort_direction).paginate(page: params[:page], per_page: 5).search(params[:search])
    respond_with do |format|
      format.html {
        render :partial => 'games/games_table' if request.xhr?
      }
    end
  end

  def show
    @used_ids = (@game.players.pluck(:user_id)) + [@game.manager.user_id]

  end

  def new
    render "games/new", layout: false
  end

  def create
    @game = Game.create(params[:game])
    respond_with @game
  end

  def edit

  end

  def best_player
    @game = Game.find(params[:game_id])
    @best_player = @game.players.pluck(:user_id)
    render 'games/best_player', layout: false
  end

  def update
    @game.update_attributes(params[:game])
    @game.players.each do |a|
      a.set_score!
      a.won!
    end
    respond_with @game

  end

  def destroy
    @game.destroy
    redirect_to games_path
  end

  private

  def game_find
    @game = Game.find(params[:id])
  end

  def user_scoped
    @users = User.scoped
  end

  def appointment_scoped
    @players = Player.scoped
  end

  def sort_column
    Game.column_names.include?(params[:sort_column]) ? params[:sort_column] : 'created_at'
  end

  def sort_direction

    %w[asc desc].include?(params[:sort_direction]) ? params[:sort_direction] : 'asc'
  end


end

app/helpers/games_helper.rb
module GamesHelper
  def games_action(g)
    actions = {}
      actions[:show] = link_to 'Show', game_path(g), class:'btn'
      actions[:edit] = link_to 'Edit', edit_game_path(g), class:'btn'
      actions[:destroy] = link_to 'Destroy', game_path(g), method: :delete,class:'btn btn-danger'
    render "shared/actions", :object => g, :actions => actions
  end

  def user_alias_by_player(player)
    user = User.find(player.user_id)
  if player.player_number
    "##{player.player_number}. #{user.alias} "
  else
    "#{user.alias}"
    end
  end

  def player_name_or_alias(player)
    if player.user.alias
    "#{player.user.alias},"
    else
      "#{player.user.name}"
    end
  end
end

app/views/games/_display_remarks.html.haml
.div2.alert.alert-info
  Remarks:
  - @game.players.each do |player|
    - if player.remark.present? && (player.remark != 0 || player.kill)
      %div{class: "#{player.user.name} remark_separator"}
        №
        = player.player_number
        .player{data:{remarks: player.remark,kill: player.kill.to_s}}
          = player.user.name
        .remark
          = player.remark if player.remark
          = "Dead" if player.kill

        .kill

  .set_remarks
    %strong
      = link_to 'Make A Remark', '', class: 'btn remark_link'

app/views/games/_drag_drop.html.haml
- can_be_player = User.where("id not in(?) ", @used_ids)

- if @game.players.size < 10
  .dragable
    .items
      - can_be_player.each do |player|
        - unless player.id == nil
          .btn.btn-inverse.noSelect.item{:data => {:id => "#{player.id}"}}
            = player.name

.dropzone-container
  = render partial: 'games/drop_zone'

app/views/games/_drop_zone.html.haml
.div1.dropzone.add.well
  .progress
  %strong
    - @game.players.each do |player|
      - unless player.id.nil?
        %div{class: "#{player.user.name} btn-group item2 alive"}
          %a{class: "btn btn-primary btn_first"}
            %i.icon-user.icon-white
            #{player.user.name}
            № #{player.player_number}

          = link_to '#', {class: "btn btn-primary dropdown-toggle"} do
            %span.caret
          %ul.dropdown-menu
            %li
              =link_to game_player_path(@game, player), method: :delete do
                Delete
                %i.icon-trash

app/views/games/_form.html.haml
= form_for @game do |g|
  %div
    = g.label :description
    %br/
    = g.text_field :description

  %div
    = g.select :game_manager, options_for_select(@users.map {|user| [user.alias, user.id]})

  %div
    = g.submit

:javascript
  $('input[type="submit"]').click(function(){
    var description = $('#game_description').val()
        pass = true;

    if (!description) {
      $('#game_description').attr('placeholder', 'cant be blank');
      pass = false;
    }
    return pass;
  })

app/views/games/_formedit.html.haml
= simple_form_for @game do |f|
  .span6
    .well
      = f.input :description, as: :text, input_html: { placeholder: "Enter description", rows: 3}
    .well
      = f.radio_button :game_status, 'open', {id: "game_open_game"}
      = f.label "open_game", 'open'
      = f.radio_button :game_status, 'closed', {id: "game_closed_game"}
      = f.label "closed_game", 'closed'
    .well
      = f.radio_button :result, 'red', {id: "game_won_red"}
      = f.label "won_red", 'red'
      = f.radio_button :result, 'black', {id: "game_won_black"}
      = f.label "won_black", 'black'
      = f.input :first_killed_sheriff
    .form-actions
      = f.submit 'Update', class: 'btn btn-inverse'

app/views/games/_game_players.html.haml
.game_players
  - @game.players.each do |player|
    .span2.well
      %br
        %b name:
        = "#{player.user.name}"
      %br
        %b role:
        = "#{player.role}"
      %br
        %b score:
        = "#{player.score}"
      %br
        %b number:
        = "#{player.player_number}"

app/views/games/_game_status.html.haml
.finish_game
  .well
    = f.radio_button :game_status, 'open', {id: "game_open_game"}
    = f.label "open_game", 'open'
    = f.radio_button :game_status, 'closed', {id: "game_closed_game"}
    = f.label "closed_game", 'closed'
  .well
    = f.radio_button :result, 'red', {id: "game_won_red"}
    = f.label "won_red", 'red'
    = f.radio_button :result, 'black', {id: "game_won_black"}
    = f.label "won_black", 'black'
    = f.input :first_killed_sheriff

app/views/games/_games_table.html.haml
%table.table.table-striped.table-bordered.bordered.zebra

  %thead
    %tr
      %th{:style => 'width: 10%'} ID
      %th{:style => 'width: 10%'}=sortable 'description','Description'
      %th{:style => 'width: 10%'} Manager
      %th{:style => 'width: 40%'} players
      %th{:style => 'width: 10%'}= sortable 'game_status', 'Game Status'
      %th{:style => 'width: 30%'}= sortable 'best_player', 'Best Player'
      %th{:style => 'width: 10%'}= sortable 'result', 'Result'

      %th{:style => 'width: 10%'}
      -#%th{:style => 'width: 10%'} Update
      -#%th{:style => 'width: 10%'} Destroy
    - @games.each do |game|
      %tr
        %td= game.game_ref
        %td= game.description
        %td= game.manager.user.name
        %td
          -game.players.each do |player|
            - if player.role
              =image_tag "#{player.role}.jpeg", :id=> "role",:rel => 'popover', 'data-content' => "#{user_alias_by_player player}"
            - else
              = player_name_or_alias(player)
        %td= game.game_status
        %td= game.best_player
        %td= game.result

        %td
          .btn-group
            =link_to 'Actions', '', class: 'btn btn-primary dropdown-toggle'
            =link_to '', class: 'btn btn-primary dropdown-toggle' do
              %span.caret
            %ul.dropdown-menu
              %li
                = link_to game_path(game) do
                  %i.icon-th
                  Show
              %li
                = link_to edit_game_path(game) do
                  %i.icon-pencil
                  Edit
              %li
                = link_to game_path(game), method: :delete do
                  %i.icon-trash
                  Destroy
- if can? :create, @game
  .new
    = link_to "New", new_game_path, rel: 'facebox', class:'btn btn-primary'
#pagination= will_paginate @games
:javascript
  $(function () {
      $("img#role").each(function() {
        $(this).popover({html: true, trigger: 'hover',placement: 'top',delay: { show: 100, hide: 100 }});
      });
  });

app/views/games/_player_roles.html.haml
.top_145_left_160.show_hide_role_container.hidden
  - @game.players.each do |player|
    %div
      .player_div
        .player
          = player.user.alias
      .display_role_div
        %span.display_role
          = player.role

app/views/games/_remarks.html.haml
.div2
  Remarks:
  - @game.appointments.each do |player|
    - if player.remark.present? && player.remark != 0

      .remark_separator
        .player
          = player.user.name
        .remark
          = player.remark
  .set_remarks
    %strong
      = link_to 'Make A Remark', get_remarks_game_appointment_path(@game), rel: 'facebox', class: 'btn'

app/views/games/_timer.html.haml
.countdown.remark
  60
.start.btn
  Start


-#:javascript
-#  $('.start').click(function(){
-#    //$(this).addClass('hidden')
-#    return setInterval(doUpdate, 1000);
-#
-#  });
-#
-#  $('.stop').click(function(){
-#
-#  })
-#
-#
-#    var doUpdate = function() {
-#      $('.countdown').each(function() {
-#        var count = parseInt($(this).html());
-#        if (count !== 0) {
-#          $(this).html(count - 1);
-#        } else {
-#          $(this).html(60)
-#
-#        }
-#      });
-#    };
-#
-#    // Schedule the update to happen once every second

app/views/games/index.html.haml
%ul.nav.nav-tabs
  %li.active
    = link_to 'Games'
  %li
    = link_to 'Scores', scores_path
  - if can? :manage_roles, @user
    %li
      = link_to 'Users', users_path
%h4 Games list

= form_tag @game, method: :get,class: 'form-search', id: 'search' do
  .input-append
    = text_field_tag :search, params[:search], class: 'span2 search-query'
    = submit_tag 'Search', class: 'btn'
#sortable_table= render 'games/games_table'

app/views/games/new.html.haml
= render 'games/form'

app/views/games/show.html.haml
.game_content
  %div
    %span
      Description:
      %strong
        = @game.description
        - if can? :update, @game
          %span.finish.btn.btn-inverse
            = link_to 'Finish Game', game_best_player_path(@game), rel: 'facebox'

  %div
    %span
      Manager:
      %strong
        = @game.manager.user.name

  %div{data: {id: "#{@game.id}"}, class: 'game'}
    %span
      ID:
      %strong
        = @game.id
  %div
    %span
      Status:
      %strong
        = @game.game_status
  - unless @game.status_open?
    - if @game.result.present?
      %div
        %span
          Won:
          %strong
            = @game.result
    - if @game.best_player.present?
      %div
        %span
          Best Player:
          %strong
            = @game.best_player
  .clock_widget.hidden
    .clock
    .start.btn.btn-success START
    .stop.btn.btn-inverse STOP
    .reset.btn.btn-danger RESET
  .toggleShowClock.btn.btn-primary Show / Hide Clock
.row
  = render  @game.status_open? ? 'games/drag_drop' :  'games/game_players'

  - if @game.players.size >= 10 && @game.status_open?
    = render 'games/display_remarks'
    = render 'players/remarks'
    = render 'players/role'
    = render 'games/player_roles'
    -#= render 'games/timer'
  .span6.pull-right.main_buttons
    - if @game.players.present? && @game.status_open?
      .remove_all
        = link_to 'Rolify', set_role_game_player_path(@game, @players), rel: '', class: 'btn rolify'
      .remove_all
        = link_to 'Remove All', destroy_all_game_player_path(@game, @players), method: :delete, class: 'btn'
        -#= link_to 'Show/Hide Roles', '', class: 'btn show_hide_role'

:javascript
  $(function(){
    new Drag_Drop();
    new Roles();
    new ValidateRolesUniqurness();
  })

  $(document).ready(function() {
      var clock;

      clock = $('.clock').FlipClock(60, {
          clockFace: 'MinuteCounter',
          countdown: true,
          callbacks: {
              stop: function() {
              }
          }
      });
      clock.stop();
      var time  = clock.getTime();
      $('.start').on('click', function(){

          clock.setTime(time.time);
          clock.start();
      });
      $('.stop').on('click', function(){
        clock.stop();
      });

      $('.reset').on('click', function(){
        clock.stop();
        clock.setTime(60);
      });

      $('.toggleShowClock').on('click',function(){
        $('.clock_widget').toggleClass('hidden');
      });
  });