config/routes.rb
Mafia::Application.routes.draw do

  devise_for :users, :path_prefix => 'my'
  resources :users do
    resources :player_roles
  end

  resources :games do
    get :best_player
    resources :rounds
    resources :players do
      collection do
        post :create_bunch
        put :put_roles
        put :put_remarks
      end

      member do
        #get :score
        get :set_role
        delete :destroy_all
        get :get_remarks
      end
    end
  end

  resources :scores
  root :to => 'games#index'
end

app/models/player.rb
class Player < ActiveRecord::Base
  include Score
  resourcify

  belongs_to :game
  belongs_to :user

  PLAYER_ROLE = ['don','mafia','sheriff','citizen'].freeze
  PLAYER_TEAM = ['red', 'black'].freeze

  attr_accessible :user_id, :game_id, :id, :role, :team, :player_number, :remark, :kill, :nominate
  validates :user_id, presence: true
  validates :role, :inclusion => { :in => PLAYER_ROLE }, on: :update
  validates :team, :inclusion => { :in => PLAYER_TEAM }, on: :update

  delegate :result_black?, :result_red?, to: :game

  #def methods  is_don? is_mafia? is_sheriff? is_citizen?
  PLAYER_ROLE.each do |type|
    define_method("is_#{type}?") {role.to_s == type}
  end

  #def methods team_red? team_black?
  PLAYER_TEAM.each do |type|
    define_method("team_#{type}?") {team.to_s == type}
  end
end

app/models/player/score.rb
module Player::Score

  def set_score!
    if game.result_red?
      if team_red?
        score = is_sheriff? ? 4 : 3
      elsif team_black?
        score = is_don? ? -1 : 0
      end
    elsif game.result_black?
      if team_black? &&
        score = is_don? ? 5 : 4
      elsif is_sheriff? && game.first_killed_sheriff
        score = -1
      elsif team_red?
        score = 0
      end
    end
    update_attribute(:score, score)
  end

  def set_team!
    (is_don? || is_maffia?) ? team = "black" : team = "red"
    update_attribute(:team, team)
  end

  def won!
    game.result_red? ? red_winner : black_winner
  end

  private

  def red_winner
    team_red? ? flag = true : flag = false
    update_attribute(:won, flag)
  end

  def black_winner
    team_red? ? flag = false : flag = true
    update_attribute(:won, flag)
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController

  before_filter :find_game
  respond_to :html, :js

  def create
    Rails.logger.info params
    @player = @game.players.build(params[:player])
    @player.save
    respond_with @game, @player, :location => game_path(@game)
  end

  def create_bunch
    @game.update_attributes(players_attributes: params.fetch(:player_data, []))
    render nothing: true
  end

  def show

  end

  def destroy
    @player = @game.players.find(params[:id])
    @player.destroy
    respond_with @game, @player, :location => game_path(@game)
  end

  def destroy_all
    @players = @game.players.all.map(&:destroy)
    respond_with @game, @player, :location => game_path(@game)
  end

  def set_role
    Rails.logger.info params
    @player = @game.players(params[:player])
    #render 'players/role', layout: false
  end

  def put_roles
    @game.update_attributes(params.fetch(:game, {}))
    PlayerService.set_team!(@game.players)
    respond_with(@game, @player) do |format|
      format.html { render partial: 'games/drop_zone' if request.xhr? }
    end
  end

  def get_remarks
    @player = @game.players(params[:player])
  end

  def put_remarks
    @game.update_attributes(params.fetch(:game, {}))
    respond_with(@game, @player) do |format|
      format.html { render partial: 'games/display_remarks' if request.xhr? }
      format.json
    end
  end

  private

  def find_game
    @game = Game.find(params[:game_id])
  end
end

app/views/players/_remarks.html.haml
.top_145_left_160.hidden.put_remarks
  = form_for @game, :url => put_remarks_game_players_path(@game) do |f|
    = f.fields_for :players do |a_f|
      - unless a_f.object_id.nil?
        %div
          .player
            = a_f.object.player_number
          %span.role_section
            = a_f.radio_button :remark, '0', {id: "game_appointments_attributes_#{a_f.object.id}_remarks_0"}
            = f.label "appointments_attributes_#{a_f.object.id}_remarks_0", "0"
          %span.role_section
            = a_f.radio_button :remark, '1', {id: "game_appointments_attributes_#{a_f.object.id}_remarks_1"}
            = f.label "appointments_attributes_#{a_f.object.id}_remarks_1", "1"
          %span.role_section
            = a_f.radio_button :remark, '2', {id: "game_appointments_attributes_#{a_f.object.id}_remarks_2"}
            = f.label "appointments_attributes_#{a_f.object.id}_remarks_2", "2"
          %span.role_section
            = a_f.radio_button :remark, '3', {id: "game_appointments_attributes_#{a_f.object.id}_remarks_3"}
            = f.label "appointments_attributes_#{a_f.object.id}_remarks_3", "3"
          %span.role_section
            = a_f.radio_button :remark, '4', {id: "game_appointments_attributes_#{a_f.object.id}_remarks_4"}
            = f.label "appointments_attributes_#{a_f.object.id}_remarks_4", "4"
          %span.role_section
            = a_f.check_box :kill, {id: "game_appointments_attributes_#{a_f.object.kill}_#{a_f.object.id}K"}, "true", "false"
            = f.label "appointments_attributes_#{a_f.object.kill}_#{a_f.object.id}K", "K"
          %span.role_section
            = a_f.check_box :nominate, {id: "game_appointments_attributes_#{a_f.object.nominate}_#{a_f.object.id}N"}, "true", "false"
            = f.label "appointments_attributes_#{a_f.object.nominate}_#{a_f.object.id}N", "N"

    = f.submit 'Set Remarks/Nominate/Kill', class: 'btn'
:javascript
  $(function(){
    new Remarks();
  })

app/views/players/_role.html.haml
.top_145_left_160.put_role.hidden
  = form_for @game, :url => put_roles_game_players_path(@game) do |f|
    = f.fields_for :players do |a_f|
      - unless a_f.object_id.nil?
        .roles_content
          .player
            %span.role_selection
              = a_f.text_field :player_number
            = a_f.object.user.name

        .role_name
          %span.role_section
            = a_f.radio_button :role, 'don', {id: "game_appointments_attributes_#{a_f.object.id}_role_don"}
            = f.label "appointments_attributes_#{a_f.object.id}_role_don", "DON"
          %span.role_section
            = a_f.radio_button :role, 'mafia', {id: "game_appointments_attributes_#{a_f.object.id}_role_mafia"}
            = f.label "appointments_attributes_#{a_f.object.id}_role_mafia", "MAFIA"
          %span.role_section
            = a_f.radio_button :role, 'sheriff', {id: "game_appointments_attributes_#{a_f.object.id}_role_sherif"}
            = f.label "appointments_attributes_#{a_f.object.id}_role_sherif", "SHERIF"
          %span.role_section
            = a_f.radio_button :role, 'citizen', {id: "game_appointments_attributes_#{a_f.object.id}_role_citizen",checked:true}
            = f.label "appointments_attributes_#{a_f.object.id}_role_citizen", "CITIZEN"
    = f.submit 'Set Roles', class: 'btn'

app/views/players/score.html.haml
= form_for @game, url: set_score_game_players_path(@game) do |f|
  = f.fields_for :players do |a_f|
    = a_f.radio_button :score, '0'
    = f.label